[tool.poetry]
name = "purplship.dhl_universal"
version = "2021.11"
homepage="https://docs.purplship.com"
repository="https://github.com/purplship/purplship"
description = "Purplship - DHL Universal Tracking Extension"
authors = ["Purplship <hello@purplship.com>"]
license = "Apache License Version 2.0"
readme = "README.md"
packages = [{ include = "purplship" }]
classifiers=[
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
]

[tool.poetry.dependencies]
python = "^3.7"
"purplship" = "^2021.6"
"carrier.dhl_universal" = ""

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0", "setuptools!=50.0"]
build-backend = "poetry.core.masonry.api"
