language: python
python:
  - "3.6.5"
install:
  - pip install coverage
  - pip install codecov
  - pip install mypy
  - pip install . --process-dependency-links

script: 
  - coverage run --include='purplship/*' -m unittest -v
  - mypy purplship/ --no-strict-optional --no-warn-return-any --no-warn-unused-configs

after_success:
  - coverage report -m
  - codecov