version: '3'

services:
  api:
    image: karrio/ee
    build:
      context: ./
      dockerfile: docker/dev.insiders.Dockerfile
    container_name: api
    env_file: .env
    environment:
      DATABASE_HOST: "db"
    volumes:
      - .:/karrio/app/
      - karriostatics:/karrio/static
    ports:
      - "5002:5002"
    depends_on:
      - db
      - redis
    networks:
      - db_network
      - web_network
    command: karrio runserver 0.0.0.0:5002

  worker:
    image: karrio/ee
    container_name: worker
    env_file: .env
    environment:
      DATABASE_HOST: "db"
    volumes:
      - .:/karrio/app/
      - karriodata:/karrio/data
    depends_on:
      - db
    networks:
      - db_network
    command: karrio run_huey -w 2

  db:
    extends:
      file: docker-compose.yml
      service: db

  redis:
    extends:
      file: docker-compose.yml
      service: redis

volumes:
  redisdata: null
  karriodata: null
  karriostatics:
    driver: local

networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
