version: '3'

services:
  karrio:
    image: karrio/test
    build:
      context: ./
      dockerfile: docker/dev.test.Dockerfile
    container_name: karrio
    env_file: .env
    environment:
      DATABASE_HOST: "db"
    volumes:
      - .:/karrio/app/
    ports:
      - "5002:5002"
    depends_on:
      - db
      - redis
    networks:
      - db_network

  redis:
    extends:
      file: docker-compose.yml
      service: redis

  db:
    extends:
      file: docker-compose.yml
      service: db

volumes:
  redisdata:

networks:
  db_network:
    driver: bridge
