version: '3'

services:
  db:
    container_name: db
    image: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: /var/lib/postgresql/data/karrio

  karrio:
    container_name: karrio
    image: danh91.docker.scarf.sh/karrio/server:2022.8.15
    restart: unless-stopped
    ports:
      - "5002:5002"
    depends_on:
      - db
    environment:
      DEBUG_MODE: True
      DATABASE_NAME: "db"
      DATABASE_HOST: "db"
      DATABASE_USERNAME: "postgres"
      DATABASE_PASSWORD: "postgres"
      DETACHED_WORKER: False

  dashboard:
    container_name: dashboard
    image: danh91.docker.scarf.sh/karrio/dashboard:2022.8.15
    ports:
      - "3000:3000"
    depends_on:
      - karrio
    environment:
      - 'NEXT_PUBLIC_KARRIO_API_URL=http://localhost:5002'
      - 'KARRIO_HOSTNAME=http://karrio:5002'
      - 'NEXTAUTH_URL=http://localhost:3000'
      - JWT_SECRET="RANDOM_SECRET"
