version: '3'

services:
  karrio:
    image: karrio/dev
    build:
      context: ./
      dockerfile: docker/dev.Dockerfile
    container_name: karrio
    env_file: .env
    environment:
      DATABASE_HOST: "db"
    volumes:
      - .:/karrio/app/
      - karriostatics:/karrio/static
    ports:
      - "5002:5002"
    depends_on:
      - db
      - redis
    networks:
      - db_network
      - web_network
    command: karrio runserver 0.0.0.0:5002

  worker:
    image: karrio/dev
    container_name: worker
    env_file: .env
    environment:
      DATABASE_HOST: "db"
    volumes:
      - .:/karrio/app/
      - karriodata:/karrio/data
    depends_on:
      - db
    networks:
      - db_network
    command: karrio run_huey -w 2

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - karriostatics:/static
    networks:
      - web_network
    depends_on:
      - karrio

  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: /var/lib/postgresql/data/karrio-dev
    ports:
      - "5432:5432"
    networks:
      - db_network

  redis:
    restart: always
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  redisdata:
  karriodata:
  karriostatics:
    driver: local

networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
