version: '3'

services:
  pship:
    build:
      context: ./
      dockerfile: ./.docker/Dockerfile
    image: purplship/purplship-server:latest
    container_name: pship
    env_file: .env
    volumes:
      - .:/temp/dev
      - purplship-statics:/static
    ports:
      - "5002:5002"
    depends_on:
      - db
    networks:
      - db_network
      - web_network
    entrypoint: |
      bash -c "bash -s <<EOF
      cd /temp/dev &&
      pip install -f https://git.io/purplship -r requirements.dev.txt --upgrade --src /temp/src &&
      cd /app &&
      if [[ "${TEST:-False}" == "True" ]];
      then
        source /temp/dev/scripts.sh && test
      else
        export MULTI_TENANT_ENABLE=${MULTI_TENANT_ENABLE:-False}
        export RELOAD=${RELOAD:-False}
        source /temp/dev/scripts.sh && add_data
        ./entrypoint.sh
      fi
      EOF"

  nginx:
    image: "nginx:latest"
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - purplship-statics:/static
    networks:
      - web_network
    depends_on:
      - pship

  db:
    image: postgres
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: /var/lib/postgresql/data/pship
    ports:
      - "5432:5432"
    networks:
      - db_network

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
    networks:
      - db_network

volumes:
  purplship-statics:
    driver: local

networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge