[build]
ignore = "/bin/false"
base = "purpleserver/"
publish = "site/"
environment = { PYTHON_VERSION = "3.7" }
command = """
pip3 install mkdocs-material==6.2.5 mkdocs==1.1.2 && mkdocs build  -f ../mkdocs.yml -d ${PWD}/site
"""
