version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
  purpleserver:
    image: python:3.8
    working_dir: /app
    environment:
      - DEBUG_MODE=True
      - ALLOWED_HOSTS=*
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=db
      - DATABASE_ENGINE=postgresql_psycopg2
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    volumes:
      - .:/app
      - ./.venv/temp:/app/.venv
    ports:
      - "80:8000"
    depends_on:
      - db
    entrypoint: |
      bash -c "bash -s <<EOF
      . ./scripts.sh
      activate_env || create_env && activate_env
      pip install psycopg2 &&
      test_install &&
      test
      EOF"