[tool.poetry]
name = "carrier.asendia_us"
version = "2021.2.2"
description = "Asendia US API Schemas Python Data Types library"
repository="https://github.com/karrio/karrio"
homepage="https://github.com/karrio/karrio/tree/main/carrier.asendia_us"
authors = ["Karrio <hello@karrio.com>"]
license = "Apache-2.0"
readme = "README.md"
packages = [
    { include = "asendia_us_lib" }
]
classifiers = [
	"Intended Audience :: Developers",
	"Operating System :: OS Independent",
	"Programming Language :: Python :: 3",
	"License :: OSI Approved :: Apache Software License",
]

[tool.poetry.dependencies]
python = "^3.6"
jstruct = ""

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0", "setuptools!=50.0"]
build-backend = "poetry.core.masonry.api"
