# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: puprlship-server

on: [push]

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run Tests
      run: |
        sudo chown -R 1000 ./
        docker-compose -f docker-compose.test.yml run --rm pship bash -c '
          cd app && pip install -r requirements.dev.txt && cd -
          purplship migrate &&
          purplship test --failfast purplship.server.proxy.tests &&
          purplship test --failfast purplship.server.pricing.tests &&
          purplship test --failfast purplship.server.manager.tests &&
          purplship test --failfast purplship.server.events.tests &&
          purplship test --failfast purplship.server.graph.tests
        '

  tests-ee:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run ee Tests
      run: |
        sudo chown -R 1000 ./
        docker-compose -f docker-compose.test.yml run --rm pship bash -c '
          cd app && pip install -r requirements.ee.dev.txt && cd -
          purplship migrate &&
          purplship test --failfast purplship.server.proxy.tests &&
          purplship test --failfast purplship.server.pricing.tests &&
          purplship test --failfast purplship.server.manager.tests &&
          purplship test --failfast purplship.server.events.tests &&
          purplship test --failfast purplship.server.graph.tests &&
          purplship test --failfast purplship.server.orgs.tests
        '
