# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: karrio-tests

on: [push]

jobs:
  sdk-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v2
      - name: Run Tests
        run: |
          pip install --upgrade pip
          ./bin/setup-sdk-env.sh &&
          ./bin/run-sdk-typecheck.sh &&
          ./bin/run-sdk-tests.sh

  server-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v2
      - name: Run Tests
        run: |
          apt update -y && apt install -y libpango1.0-0 libpangoft2-1.0-0 gcc ghostscript
          . ./bin/setup-server-env.sh &&
          karrio migrate &&
          karrio test --failfast karrio.server.proxy.tests &&
          karrio test --failfast karrio.server.pricing.tests &&
          karrio test --failfast karrio.server.manager.tests &&
          karrio test --failfast karrio.server.events.tests &&
          karrio test --failfast karrio.server.graph.tests &&
          karrio test --failfast karrio.server.orders.tests
